repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: requirements-txt-fixer
    - id: check-merge-conflict
    - id: check-json
    - id: double-quote-string-fixer
    - id: check-ast
    - id: check-added-large-files
      args: ['--maxkb=10000']
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        additional_dependencies: ['flake8-docstrings',
                                  'flake8-eradicate',
                                  'flake8-polyfill',
                                  'flake8-print']
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.9.0
  hooks:
    - id: reorder-python-imports
